#!/usr/bin/env python3
"""生成魔导书补充数据：为不足的子分类各补充约100条"""
import json
from pathlib import Path

DATA = Path(__file__).resolve().parent.parent / "data"

# ============================================================
# 1. lighting/lighting.json — 灯光效果 (现有10条 → 补106条)
# ============================================================
LIGHTING_NEW = [
    {"name": "晨光清新", "tags": "morning light, fresh, soft sunrise, cool tones, dew", "style": "general"},
    {"name": "午后阳光", "tags": "afternoon sun, warm, golden, harsh shadows, bright", "style": "general"},
    {"name": "黄昏余晖", "tags": "dusk light, twilight, warm orange, fading light, calm", "style": "general"},
    {"name": "多云柔光", "tags": "overcast, soft diffused, cloudy, no harsh shadows, even lighting", "style": "general"},
    {"name": "窗格光影", "tags": "window light, light patterns, shadows, indoor, natural light", "style": "general"},
    {"name": "树影斑驳", "tags": "dappled light, leaves shadow, forest light, natural patterns, sunlight through trees", "style": "general"},
    {"name": "水波反光", "tags": "water reflection, caustics, rippling light, aqua, shimmering", "style": "general"},
    {"name": "聚光灯", "tags": "spotlight, focused light, center stage, dramatic, highlight", "style": "general"},
    {"name": "顶光", "tags": "top lighting, overhead light, dramatic shadows, hollow eyes", "style": "general"},
    {"name": "侧光", "tags": "side lighting, half shadow, dramatic, chiaroscuro, contrast", "style": "general"},
    {"name": "底光", "tags": "under lighting, up lighting, eerie, horror, ghostly", "style": "general"},
    {"name": "轮廓光", "tags": "rim light, edge light, backlight, halo effect, outline", "style": "general"},
    {"name": "眼神光", "tags": "catchlight, eye reflection, sparkle, lively eyes, bright eyes", "style": "general"},
    {"name": "环形灯", "tags": "ring light, soft even light, beauty lighting, portrait light, shadowless", "style": "general"},
    {"name": "柔光箱", "tags": "softbox, studio lighting, professional, even illumination, soft shadows", "style": "general"},
    {"name": "硬光", "tags": "hard light, direct light, sharp shadows, high contrast, bold", "style": "general"},
    {"name": "灯笼光", "tags": "lantern light, warm glow, traditional, festive, orange hue", "style": "general"},
    {"name": "篝火", "tags": "campfire light, warm flicker, orange glow, outdoors, cozy", "style": "general"},
    {"name": "闪电", "tags": "lightning, bright flash, stark, momentary, blue white", "style": "general"},
    {"name": "极光", "tags": "aurora, northern lights, green glow, sky, magical, ethereal", "style": "general"},
    {"name": "荧光棒", "tags": "glowstick, neon colors, concert, rave, colorful glow", "style": "general"},
    {"name": "LED灯带", "tags": "LED strip, colorful lights, modern, RGB, ambient", "style": "general"},
    {"name": "吊灯", "tags": "chandelier light, crystal, elegant, warm, sparkling", "style": "general"},
    {"name": "台灯", "tags": "desk lamp, study light, focused, warm, cozy", "style": "general"},
    {"name": "路灯", "tags": "street light, sodium lamp, orange glow, night, urban", "style": "general"},
    {"name": "车灯", "tags": "headlights, car lights, bright beams, night drive, dual lights", "style": "general"},
    {"name": "显示屏光", "tags": "screen light, monitor glow, blue light, cyber, digital", "style": "general"},
    {"name": "火光", "tags": "firelight, warm glow, flames, flickering, intense", "style": "general"},
    {"name": "熔岩光", "tags": "lava glow, molten, red orange, volcanic, intense heat", "style": "general"},
    {"name": "魔法光", "tags": "magic light, glowing, fantasy, sparkling, enchanted", "style": "general"},
    {"name": "圣光", "tags": "holy light, divine glow, radiant, pure white, heavenly", "style": "general"},
    {"name": "暗光", "tags": "dim light, low light, shadowy, murky, mysterious", "style": "general"},
    {"name": "烛光", "tags": "candle light, warm, soft, romantic, gentle glow", "style": "general"},
    {"name": "油灯", "tags": "oil lamp light, vintage, warm yellow, antique, cozy", "style": "general"},
    {"name": "霓虹招牌", "tags": "neon sign, bright, colorful, tube lights, urban night", "style": "general"},
    {"name": "荧光", "tags": "fluorescent light, cold white, clinical, bright, cool tone", "style": "general"},
    {"name": "白炽灯", "tags": "incandescent, warm yellow, soft, homey, traditional", "style": "general"},
    {"name": "激光", "tags": "laser light, focused beam, bright, colorful, sci fi", "style": "general"},
    {"name": "慢速同步", "tags": "slow sync flash, ghostly, motion blur, long exposure, creative", "style": "general"},
    {"name": "双重曝光", "tags": "double exposure, layered, ghostly, artistic, surreal", "style": "general"},
    {"name": "逆光", "tags": "back light, contre-jour, silhouette, rim light, dramatic", "style": "general"},
    {"name": "偏光", "tags": "polarized light, glare reduction, saturated colors, clear", "style": "general"},
    {"name": "全光", "tags": "full light, brightly lit, no shadows, clear, detailed", "style": "general"},
    {"name": "夜景", "tags": "night scene, dark, city lights, stars, moonlit", "style": "general"},
    {"name": "黄昏", "tags": "twilight, blue hour, dusk, gradient sky, serene", "style": "general"},
    {"name": "拂晓", "tags": "dawn, first light, sunrise, golden pink, new day", "style": "general"},
    {"name": "正午", "tags": "noon, bright sunlight, harsh, high contrast, overhead", "style": "general"},
    {"name": "阴天", "tags": "cloudy day, flat lighting, soft, gray, diffused", "style": "general"},
    {"name": "雾天", "tags": "foggy, misty, hazy, soft glow, atmospheric", "style": "general"},
    {"name": "雨天", "tags": "rainy, wet surfaces, gray, reflections, moody", "style": "general"},
    {"name": "雪天", "tags": "snowy, white, bright, reflective, cold blue", "style": "general"},
    {"name": "闪电风暴", "tags": "thunderstorm, lightning, dark clouds, dramatic, intense", "style": "general"},
    {"name": "彩虹", "tags": "rainbow, colorful, spectrum, after rain, bright", "style": "general"},
    {"name": "彩光", "tags": "colored light, gel lighting, stage, party, vibrant", "style": "general"},
    {"name": "全息投影", "tags": "holographic, iridescent, futuristic, shifting colors, sci fi", "style": "general"},
    {"name": "生物发光", "tags": "bioluminescence, glowing, underwater, fantasy, blue green", "style": "general"},
    {"name": "磷光", "tags": "phosphorescent, glow in dark, eerie, green, ghostly", "style": "general"},
    {"name": "闪电光", "tags": "strobe light, flashing, disorienting, club, rapid", "style": "general"},
    {"name": "光绘", "tags": "light painting, long exposure, streaks, creative, artistic", "style": "general"},
    {"name": "日光", "tags": "daylight, natural light, balanced, white, clear", "style": "general"},
    {"name": "暖光", "tags": "warm light, yellow orange, cozy, inviting, soft", "style": "general"},
    {"name": "冷光", "tags": "cold light, blue white, clinical, crisp, modern", "style": "general"},
    {"name": "琥珀光", "tags": "amber light, warm glow, vintage, golden, rich", "style": "general"},
    {"name": "紫光", "tags": "purple light, ultraviolet, mystical, neon, vibrant", "style": "general"},
    {"name": "红光", "tags": "red light, dramatic, intense, warning, darkroom", "style": "general"},
    {"name": "蓝光", "tags": "blue light, cool, moody, serene, technological", "style": "general"},
    {"name": "绿光", "tags": "green light, nature, eerie, monitor glow, unique", "style": "general"},
    {"name": "粉光", "tags": "pink light, soft, romantic, dreamy, pastel", "style": "general"},
    {"name": "黄光", "tags": "yellow light, warm, sunny, cheerful, bright", "style": "general"},
    {"name": "混合光", "tags": "mixed lighting, multiple sources, complex, professional, layered", "style": "general"},
    {"name": "反射光", "tags": "bounced light, indirect, soft, diffused, natural", "style": "general"},
    {"name": "折射光", "tags": "refracted light, prism, rainbow spectrum, glass, crystal", "style": "general"},
    {"name": "散射光", "tags": "scattered light, soft, widespread, gentle, shadowless", "style": "general"},
    {"name": "直射光", "tags": "direct light, harsh, focused, strong shadows, defined", "style": "general"},
    {"name": "光斑", "tags": "light spots, bokeh, lens flare, sparkling, defocused", "style": "general"},
    {"name": "夕阳", "tags": "sunset, orange red, warm, golden hour, beautiful", "style": "general"},
    {"name": "晨雾", "tags": "morning mist, fog, soft, mysterious, fresh", "style": "general"},
    {"name": "黄昏辉光", "tags": "evening glow, dusk, purple orange, calm, serene", "style": "general"},
    {"name": "半照明", "tags": "half lit, partial light, shadow play, mystery, mood", "style": "general"},
    {"name": "彩色玻璃", "tags": "stained glass, colorful patterns, church, filtered light", "style": "general"},
    {"name": "日光灯", "tags": "fluorescent tube, long, bright, cool white, office", "style": "general"},
    {"name": "射灯", "tags": "track lighting, directional, modern, gallery, focused", "style": "general"},
    {"name": "氛围灯", "tags": "ambient light, soft, surrounding, mood, gentle", "style": "general"},
    {"name": "背光", "tags": "backlit, glow behind, silhouette, ethereal, dreamy", "style": "general"},
    {"name": "闪光灯", "tags": "flash, burst, bright, instant, frozen moment", "style": "general"},
    {"name": "柔光", "tags": "soft light, gentle, diffused, flattering, smooth", "style": "general"},
    {"name": "强光", "tags": "intense light, bright, overwhelming, powerful, glaring", "style": "general"},
    {"name": "点光源", "tags": "point light, single source, focused, dramatic shadows", "style": "general"},
    {"name": "面光源", "tags": "area light, broad, soft, even, large source", "style": "general"},
    {"name": "线光源", "tags": "linear light, long thin, neon tube, edge, modern", "style": "general"},
    {"name": "环光源", "tags": "ring light, circular, even, shadowless, macro", "style": "general"},
    {"name": "星空", "tags": "starlight, night sky, twinkling, dark, serene", "style": "general"},
    {"name": "月光", "tags": "moonlight, silver, pale, night, romantic, cool", "style": "general"},
    {"name": "火光", "tags": "fire glow, warm, dancing, orange, primal", "style": "general"},
    {"name": "炉火", "tags": "hearth fire, warm, cozy, crackling, home", "style": "general"},
    {"name": "闪光", "tags": "glitter, sparkle, shiny, reflective, twinkle", "style": "general"},
    {"name": "光晕", "tags": "lens flare, glare, light streak, camera artifact, bright", "style": "general"},
    {"name": "光柱", "tags": "light shaft, volume light, beam, ray, atmospheric", "style": "general"},
    {"name": "光幕", "tags": "light curtain, wall of light, modern, entrance, dramatic", "style": "general"},
    {"name": "光路", "tags": "light trail, long exposure, movement, streak, dynamic", "style": "general"},
    {"name": "光栅", "tags": "light grid, pattern, modern, architectural, sci fi", "style": "general"},
    {"name": "光羽", "tags": "feather light, soft rays, gentle, delicate, warm", "style": "general"},
    {"name": "光尘", "tags": "dust particles, light beams, atmosphere, floating, magic", "style": "general"},
    {"name": "光纱", "tags": "veil of light, sheer, dreamy, soft focus, ethereal", "style": "general"},
    {"name": "冰光", "tags": "ice light, cold blue, frozen, crystal, sharp", "style": "general"},
]

# ============================================================
# 2. pose_action/normal_posture.json — 姿态动作 (现有10条 → 补100条)
# ============================================================
POSE_NEW = [
    {"name": "倚靠", "tags": "leaning, against wall, relaxed, casual, supported", "style": "general"},
    {"name": "交叉腿", "tags": "crossed legs, sitting, elegant, casual, feminine", "style": "general"},
    {"name": "翘二郎腿", "tags": "legs crossed, knee over knee, sitting, casual, confident", "style": "general"},
    {"name": "盘腿坐", "tags": "cross-legged, sitting, casual, floor, relaxed", "style": "general"},
    {"name": "正坐", "tags": "seiza, kneeling sit, formal, japanese, traditional", "style": "general"},
    {"name": "鸭子坐", "tags": "W sitting, legs tucked, cute, floor, childlike", "style": "general"},
    {"name": "侧坐", "tags": "side sitting, legs together, elegant, demure, feminine", "style": "general"},
    {"name": "单膝跪", "tags": "one knee, kneeling, proposal, formal, respectful", "style": "general"},
    {"name": "双膝跪", "tags": "both knees, kneeling, submissive, prayer, ground", "style": "general"},
    {"name": "匍匐", "tags": "crawling, on belly, low, stealth, military", "style": "general"},
    {"name": "仰卧", "tags": "lying on back, supine, sleeping, relaxing, looking up", "style": "general"},
    {"name": "俯卧", "tags": "lying face down, prone, resting, hiding, massage", "style": "general"},
    {"name": "侧卧", "tags": "side lying, fetal, sleeping, comfortable, relaxed", "style": "general"},
    {"name": "趴桌", "tags": "lying on desk, sleeping at desk, tired, resting head", "style": "general"},
    {"name": "抬腿", "tags": "leg up, high kick, dynamic, stretching, acrobatic", "style": "general"},
    {"name": "劈叉", "tags": "split, legs apart, flexible, gymnastics, stretching", "style": "general"},
    {"name": "弓步", "tags": "lunge, one leg forward, exercise, dynamic, stable", "style": "general"},
    {"name": "深蹲", "tags": "squatting, low, waiting, casual, street style", "style": "general"},
    {"name": "半蹲", "tags": "half squat, slight bend, playful, cute, camera pose", "style": "general"},
    {"name": "鞠躬", "tags": "bowing, respectful, japanese, greeting, formal", "style": "general"},
    {"name": "弯腰", "tags": "bending over, leaning forward, picking up, flexible", "style": "general"},
    {"name": "后仰", "tags": "leaning back, arching, looking up, relaxed, stretch", "style": "general"},
    {"name": "前倾", "tags": "leaning forward, interested, curious, attentive, reaching", "style": "general"},
    {"name": "叉腰", "tags": "hands on hips, confident, assertive, posing, strong", "style": "general"},
    {"name": "抱臂", "tags": "arms crossed, defensive, confident, thinking, cool", "style": "general"},
    {"name": "背手", "tags": "hands behind back, formal, standing, relaxed, military", "style": "general"},
    {"name": "举手", "tags": "hand up, waving, reaching, asking, greeting", "style": "general"},
    {"name": "挥手", "tags": "waving, greeting, goodbye, friendly, casual", "style": "general"},
    {"name": "飞吻", "tags": "blowing kiss, blowing kiss, flirtatious, cute, playful", "style": "general"},
    {"name": "比心", "tags": "heart hands, finger heart, cute, trendy, korean", "style": "general"},
    {"name": "剪刀手", "tags": "peace sign, v sign, victory, cute, casual, photo pose", "style": "general"},
    {"name": "OK手势", "tags": "ok hand sign, circle gesture, fine, agreement, casual", "style": "general"},
    {"name": "点赞", "tags": "thumbs up, approval, good, positive, agreement", "style": "general"},
    {"name": "竖中指", "tags": "middle finger, offensive, rebel, angry, provocative", "style": "general"},
    {"name": "枪手势", "tags": "finger gun, playful, pointing, cool, casual", "style": "general"},
    {"name": "托腮", "tags": "hand on chin, thinking, contemplative, cute, thoughtful", "style": "general"},
    {"name": "捂嘴", "tags": "hand over mouth, surprised, laughing, secret, shy", "style": "general"},
    {"name": "捂脸", "tags": "facepalm, embarrassed, frustrated, oh no, shame", "style": "general"},
    {"name": "摸头", "tags": "touching head, thinking, cute, shy, gentle", "style": "general"},
    {"name": "挠头", "tags": "scratching head, confused, embarrassed, cute, anime", "style": "general"},
    {"name": "伸懒腰", "tags": "stretching, arms up, yawning, relaxing, morning", "style": "general"},
    {"name": "打哈欠", "tags": "yawning, tired, sleepy, mouth open, morning", "style": "general"},
    {"name": "揉眼睛", "tags": "rubbing eyes, tired, sleepy, waking up, cute", "style": "general"},
    {"name": "跳舞", "tags": "dancing, moving, dynamic, rhythm, joyful", "style": "general"},
    {"name": "旋转", "tags": "spinning, twirling, dress flying, dynamic, joyful", "style": "general"},
    {"name": "跳跃", "tags": "jumping, leaping, airborne, energetic, happy", "style": "general"},
    {"name": "奔跑", "tags": "running, sprinting, fast, dynamic, action", "style": "general"},
    {"name": "走路", "tags": "walking, striding, moving, casual, directional", "style": "general"},
    {"name": "小跑", "tags": "jogging, light run, brisk, exercise, moving", "style": "general"},
    {"name": "爬行", "tags": "climbing, scrambling, upward, effort, adventurous", "style": "general"},
    {"name": "攀爬", "tags": "climbing, holding on, vertical, effort, adventurous", "style": "general"},
    {"name": "游泳", "tags": "swimming, in water, stroking, aquatic, movement", "style": "general"},
    {"name": "潜水", "tags": "diving, underwater, descending, aquatic, exploration", "style": "general"},
    {"name": "浮水", "tags": "floating, on water, relaxing, swimming pool, casual", "style": "general"},
    {"name": "倒立", "tags": "handstand, upside down, acrobatic, strength, balancing", "style": "general"},
    {"name": "瑜伽", "tags": "yoga pose, stretching, flexible, meditative, exercise", "style": "general"},
    {"name": "打坐", "tags": "meditation, lotus pose, zen, peaceful, spiritual", "style": "general"},
    {"name": "祈祷", "tags": "praying, hands together, reverent, religious, pleading", "style": "general"},
    {"name": "托举", "tags": "lifting, carrying, holding up, strength, support", "style": "general"},
    {"name": "拥抱", "tags": "hugging, embracing, affectionate, close, warm", "style": "general"},
    {"name": "牵手", "tags": "holding hands, together, couple, friendship, walking", "style": "general"},
    {"name": "搂肩", "tags": "arm around shoulder, friendly, buddy, close, supportive", "style": "general"},
    {"name": "搭肩", "tags": "hand on shoulder, casual, friendly, guiding, comforting", "style": "general"},
    {"name": "背对", "tags": "back facing, away, looking away, mysterious, turning", "style": "general"},
    {"name": "回头", "tags": "looking back, glancing back, over shoulder, dynamic", "style": "general"},
    {"name": "低头", "tags": "looking down, head down, shy, sad, reading", "style": "general"},
    {"name": "抬头", "tags": "looking up, head up,仰望, hopeful, admiring", "style": "general"},
    {"name": "歪头", "tags": "head tilt, cute, curious, playful, questioning", "style": "general"},
    {"name": "侧头", "tags": "head turned, profile, looking aside, three quarter", "style": "general"},
    {"name": "仰头", "tags": "head back, looking up, drinking, laughing, relaxing", "style": "general"},
    {"name": "俯视", "tags": "looking down from above, high angle, elevated view", "style": "general"},
    {"name": "仰视", "tags": "looking up from below, low angle, towering, worship", "style": "general"},
    {"name": "回眸", "tags": "glancing back, over shoulder, flirtatious, elegant, graceful", "style": "general"},
    {"name": "闭目", "tags": "eyes closed, peaceful, sleeping, meditating, serene", "style": "general"},
    {"name": "睁大眼", "tags": "wide eyes, surprised, shocked, innocent, cute", "style": "general"},
    {"name": "眨眼", "tags": "winking, one eye, playful, flirtatious, mischievous", "style": "general"},
    {"name": "眯眼", "tags": "squinting, suspicious, smiling eyes, happy, looking", "style": "general"},
    {"name": "噘嘴", "tags": "pouting, pouty lips, upset, cute, sulking", "style": "general"},
    {"name": "微笑", "tags": "smiling, happy, gentle, warm, friendly", "style": "general"},
    {"name": "大笑", "tags": "laughing, big smile, joyful, open mouth, happy", "style": "general"},
    {"name": "哭泣", "tags": "crying, tears, sad, emotional, crying face", "style": "general"},
    {"name": "惊讶", "tags": "surprised, shocked, mouth open, eyes wide, amazed", "style": "general"},
    {"name": "生气", "tags": "angry, furious, mad, frowned, upset", "style": "general"},
    {"name": "害羞", "tags": "embarrassed, blushing, shy, timid, flushed", "style": "general"},
    {"name": "思考", "tags": "thinking, pondering, hand on chin, contemplative, thoughtful", "style": "general"},
    {"name": "投降", "tags": "surrendering, hands up, giving up, playful, caught", "style": "general"},
    {"name": "防御", "tags": "guarding, defensive stance, blocking, fighting, protecting", "style": "general"},
    {"name": "攻击", "tags": "attacking, striking, fighting, action, combat", "style": "general"},
    {"name": "握拳", "tags": "fist, clenched hand, determined, angry, ready", "style": "general"},
    {"name": "挥拳", "tags": "punching, throwing punch, fighting, action, dynamic", "style": "general"},
    {"name": "踢腿", "tags": "kicking, leg extended, fighting, dynamic, action", "style": "general"},
    {"name": "格挡", "tags": "blocking, defending, arms up, protecting, fighting", "style": "general"},
    {"name": "瞄准", "tags": "aiming, targeting, gun pose, focused, shooting", "style": "general"},
    {"name": "持剑", "tags": "holding sword, sword stance, warrior, knight, weapon", "style": "general"},
    {"name": "挥舞", "tags": "swinging, brandishing, weapon, dynamic, motion", "style": "general"},
    {"name": "骑马", "tags": "riding horse, equestrian, mounted, cowboy, knight", "style": "general"},
    {"name": "驾驶", "tags": "driving, steering wheel, vehicle, seated, focused", "style": "general"},
    {"name": "弹奏", "tags": "playing instrument, musical, guitarist, pianist, performing", "style": "general"},
    {"name": "阅读", "tags": "reading, book, focused, learning, quiet", "style": "general"},
    {"name": "书写", "tags": "writing, pen, paper, studying, creative, desk", "style": "general"},
    {"name": "绘画", "tags": "drawing, painting, art, creative, easel, canvas", "style": "general"},
    {"name": "烹饪", "tags": "cooking, kitchen, chef, preparing food, mixing", "style": "general"},
    {"name": "进食", "tags": "eating, food, meal, dining, enjoying", "style": "general"},
    {"name": "饮酒", "tags": "drinking, beverage, glass, cheers, enjoying", "style": "general"},
    {"name": "品茶", "tags": "tea drinking, teacup, traditional, calm, ceremony", "style": "general"},
]

# ============================================================
# 3. scene/environment.json — 场景环境 (现有10条 → 补100条)
# ============================================================
SCENE_NEW = [
    {"name": "图书馆", "tags": "library, bookshelves, books, quiet, study, academic", "style": "general"},
    {"name": "教室", "tags": "classroom, school, desks, blackboard, learning, students", "style": "general"},
    {"name": "卧室", "tags": "bedroom, bed, cozy, personal, intimate, sleeping", "style": "general"},
    {"name": "客厅", "tags": "living room, sofa, couch, tv, family, relaxing", "style": "general"},
    {"name": "厨房", "tags": "kitchen, cooking, stove, counter, food, utensils", "style": "general"},
    {"name": "浴室", "tags": "bathroom, bath, shower, tub, tiles, relaxing", "style": "general"},
    {"name": "阳台", "tags": "balcony, railing, outdoor, high rise, view, plants", "style": "general"},
    {"name": "屋顶", "tags": "rooftop, skyline, open air, urban, city view", "style": "general"},
    {"name": "天台", "tags": "roof terrace, open, sky, cityscape, hanging out", "style": "general"},
    {"name": "花园", "tags": "garden, flowers, plants, path, nature, cultivated", "style": "general"},
    {"name": "庭院", "tags": "courtyard, traditional, garden, peaceful, enclosed", "style": "general"},
    {"name": "阳台花园", "tags": "rooftop garden, plants, urban, green, terrace", "style": "general"},
    {"name": "公园", "tags": "park, grass, trees, bench, walking, nature", "style": "general"},
    {"name": "游乐场", "tags": "playground, slides, swings, children, fun, colorful", "style": "general"},
    {"name": "泳池", "tags": "swimming pool, water, blue, diving, summer, resort", "style": "general"},
    {"name": "海滩", "tags": "beach, sand, ocean, waves, seashells, coastline", "style": "general"},
    {"name": "码头", "tags": "pier, dock, water, boats, harbor, seaside", "style": "general"},
    {"name": "港口", "tags": "harbor, port, ships, containers, maritime, busy", "style": "general"},
    {"name": "灯塔", "tags": "lighthouse, coast, tower, light, sea, guiding", "style": "general"},
    {"name": "灯塔夜景", "tags": "lighthouse at night, beacon, dark, stars, romantic", "style": "general"},
    {"name": "山脉", "tags": "mountain, peak, snow, rocky, hiking, majestic", "style": "general"},
    {"name": "山谷", "tags": "valley, between mountains, river, green, scenic", "style": "general"},
    {"name": "河流", "tags": "river, water, flowing, banks, bridge, nature", "style": "general"},
    {"name": "瀑布", "tags": "waterfall, cascading, water, mist, powerful, nature", "style": "general"},
    {"name": "湖泊", "tags": "lake, still water, reflection, calm, peaceful", "style": "general"},
    {"name": "森林", "tags": "forest, trees, woods, nature, path, green", "style": "general"},
    {"name": "竹林", "tags": "bamboo forest, stalks, green, japanese, tranquil", "style": "general"},
    {"name": "沙漠", "tags": "desert, sand, dunes, arid, hot, vast", "style": "general"},
    {"name": "绿洲", "tags": "oasis, palm trees, water, desert, contrast, refuge", "style": "general"},
    {"name": "草原", "tags": "grassland, prairie, tall grass, wind, open, vast", "style": "general"},
    {"name": "花田", "tags": "flower field, blossoms, colorful, nature, beautiful", "style": "general"},
    {"name": "向日葵田", "tags": "sunflower field, yellow, bright, summer, happy", "style": "general"},
    {"name": "薰衣草田", "tags": "lavender field, purple, rows, fragrant, provence", "style": "general"},
    {"name": "樱花道", "tags": "cherry blossom path, pink, petals, spring, japanese", "style": "general"},
    {"name": "枫叶林", "tags": "maple forest, red leaves, autumn, colorful, japanese", "style": "general"},
    {"name": "雪地", "tags": "snowy field, white, cold, winter, footprints", "style": "general"},
    {"name": "冰川", "tags": "glacier, ice, blue, cold, massive, arctic", "style": "general"},
    {"name": "火山", "tags": "volcano, lava, smoke, eruption, mountain, dangerous", "style": "general"},
    {"name": "洞穴", "tags": "cave, cavern, dark, stalactites, underground, mysterious", "style": "general"},
    {"name": "水晶洞", "tags": "crystal cave, glowing, minerals, purple, fantasy", "style": "general"},
    {"name": "海底", "tags": "underwater, ocean, coral, fish, deep, blue", "style": "general"},
    {"name": "珊瑚礁", "tags": "coral reef, colorful, marine, tropical, diving", "style": "general"},
    {"name": "沉船", "tags": "shipwreck, underwater, ruins, wooden, ghostly", "style": "general"},
    {"name": "都市街道", "tags": "city street, buildings, cars, sidewalk, urban, busy", "style": "general"},
    {"name": "商业街", "tags": "shopping street, stores, signs, pedestrians, lively", "style": "general"},
    {"name": "小巷", "tags": "alley, narrow, walls, shadows, urban, mysterious", "style": "general"},
    {"name": "霓虹街", "tags": "neon street, bright signs, night, cyberpunk, colorful", "style": "general"},
    {"name": "地铁站", "tags": "subway station, train, platform, underground, transit", "style": "general"},
    {"name": "火车站", "tags": "train station, platform, tracks, travelers, grand", "style": "general"},
    {"name": "飞机场", "tags": "airport, terminal, planes, travelers, modern, busy", "style": "general"},
    {"name": "咖啡厅", "tags": "cafe, coffee shop, cozy, tables, drinks, relaxed", "style": "general"},
    {"name": "餐厅", "tags": "restaurant, dining, tables, food, interior, elegant", "style": "general"},
    {"name": "酒吧", "tags": "bar, counter, drinks, dim, social, nightlife", "style": "general"},
    {"name": "酒店", "tags": "hotel, lobby, elegant, reception, luxurious", "style": "general"},
    {"name": "办公室", "tags": "office, desk, computer, work, professional, corporate", "style": "general"},
    {"name": "工厂", "tags": "factory, industrial, machinery, warehouse, manufacturing", "style": "general"},
    {"name": "仓库", "tags": "warehouse, storage, boxes, shelves, industrial, spacious", "style": "general"},
    {"name": "停车场", "tags": "parking lot, cars, concrete, outdoor, urban", "style": "general"},
    {"name": "天台花园", "tags": "rooftop garden, green roof, plants, urban oasis", "style": "general"},
    {"name": "体育场", "tags": "stadium, arena, seats, field, sports, large", "style": "general"},
    {"name": "健身房", "tags": "gym, equipment, weights, exercise, fitness, training", "style": "general"},
    {"name": "医院", "tags": "hospital, ward, beds, medical, clinical, healing", "style": "general"},
    {"name": "实验室", "tags": "laboratory, science, equipment, beakers, research, futuristic", "style": "general"},
    {"name": "教堂", "tags": "church, cathedral, stained glass, pews, religious, grand", "style": "general"},
    {"name": "寺庙", "tags": "temple, shrine, traditional, religious, asian, peaceful", "style": "general"},
    {"name": "神社", "tags": "shinto shrine, torii, japanese, traditional, sacred", "style": "general"},
    {"name": "城堡", "tags": "castle, fortress, stone, medieval, tower, royal", "style": "general"},
    {"name": "宫殿", "tags": "palace, grand, luxurious, royal, ornate, majestic", "style": "general"},
    {"name": "废墟", "tags": "ruins, ancient, collapsed, overgrown, historical, mysterious", "style": "general"},
    {"name": "墓地", "tags": "graveyard, tombstones, eerie, quiet, memorial, gothic", "style": "general"},
    {"name": "博物馆", "tags": "museum, exhibits, art, gallery, cultural, educational", "style": "general"},
    {"name": "画廊", "tags": "art gallery, paintings, display, white walls, creative", "style": "general"},
    {"name": "剧院", "tags": "theater, stage, curtains, seats, performance, dramatic", "style": "general"},
    {"name": "电影院", "tags": "cinema, movie theater, screen, seats, dark, entertainment", "style": "general"},
    {"name": "音乐厅", "tags": "concert hall, stage, orchestra, grand, acoustic, elegant", "style": "general"},
    {"name": "游戏厅", "tags": "arcade, games, machines, colorful, neon, fun", "style": "general"},
    {"name": "温泉", "tags": "hot spring, onsen, steam, water, relaxing, outdoor", "style": "general"},
    {"name": "桑拿", "tags": "sauna, steam room, hot, wooden, relaxing, health", "style": "general"},
    {"name": "水族馆", "tags": "aquarium, fish tank, tunnel, marine life, blue, educational", "style": "general"},
    {"name": "动物园", "tags": "zoo, animals, enclosures, wildlife, family, educational", "style": "general"},
    {"name": "天文台", "tags": "observatory, telescope, stars, dome, astronomy, science", "style": "general"},
    {"name": "灯塔", "tags": "lighthouse, coast, beacon, tower, sea, guiding", "style": "general"},
    {"name": "风车", "tags": "windmill, rural, farm, rotating, traditional, dutch", "style": "general"},
    {"name": "磨坊", "tags": "mill, water wheel, rural, grain, traditional", "style": "general"},
    {"name": "农场", "tags": "farm, barn, animals, fields, rural, agriculture", "style": "general"},
    {"name": "牧场", "tags": "ranch, cattle, horses, fences, rural, western", "style": "general"},
    {"name": "葡萄园", "tags": "vineyard, grapes, rows, wine, hills, french", "style": "general"},
    {"name": "果园", "tags": "orchard, fruit trees, blossoms, harvest, nature", "style": "general"},
    {"name": "桥梁", "tags": "bridge, crossing, structure, river, road, architecture", "style": "general"},
    {"name": "高架桥", "tags": "viaduct, arches, tall, train, infrastructure, imposing", "style": "general"},
    {"name": "隧道", "tags": "tunnel, underground, passage, dark, train, road", "style": "general"},
    {"name": "摩天轮", "tags": "ferris wheel, carnival, amusement park, large, rotating", "style": "general"},
    {"name": "游乐园", "tags": "amusement park, rides, colorful, fun, carnival, exciting", "style": "general"},
    {"name": "嘉年华", "tags": "carnival, festival, tents, lights, games, celebration", "style": "general"},
    {"name": "祭典", "tags": "festival, matsuri, stalls, lanterns, traditional, japanese", "style": "general"},
    {"name": "烟火大会", "tags": "fireworks, display, night sky, colorful, celebration", "style": "general"},
    {"name": "圣诞市场", "tags": "christmas market, stalls, lights, winter, festive, holiday", "style": "general"},
    {"name": "太空", "tags": "outer space, stars, galaxy, void, cosmic, infinite", "style": "general"},
    {"name": "空间站", "tags": "space station, futuristic, modules, orbit, sci fi", "style": "general"},
    {"name": "赛博城", "tags": "cyberpunk city, neon, futuristic, crowded, high tech, dark", "style": "general"},
    {"name": "废土", "tags": "wasteland, post apocalyptic, ruined, barren, desolate", "style": "general"},
    {"name": "浮空岛", "tags": "floating island, fantasy, sky, waterfalls, magical, aerial", "style": "general"},
    {"name": "魔法森林", "tags": "enchanted forest, glowing, magical, fantasy, mystical", "style": "general"},
]

# ============================================================
# 4. shot/framing.json — 镜头构图 (现有11条 → 补102条)
# ============================================================
FRAMING_NEW = [
    {"name": "极特写", "tags": "extreme close-up, macro, detail, eye, intense", "style": "general"},
    {"name": "大头照", "tags": "headshot, face only, portrait, expression, focused", "style": "general"},
    {"name": "上半身", "tags": "upper body, bust shot, torso, portrait, medium close", "style": "general"},
    {"name": "中景", "tags": "medium shot, waist up, balanced, action, standard", "style": "general"},
    {"name": "七分身", "tags": "three quarter shot, knee up, full figure, balanced", "style": "general"},
    {"name": "全身", "tags": "full body, full shot, entire figure, outfit, standing", "style": "general"},
    {"name": "远景", "tags": "long shot, wide, full scene, environment, small figure", "style": "general"},
    {"name": "极远景", "tags": "extreme long shot, vast, landscape, tiny figure, epic", "style": "general"},
    {"name": "低角度", "tags": "low angle, looking up, heroic, towering, powerful", "style": "general"},
    {"name": "高角度", "tags": "high angle, looking down, vulnerable, overview, top down", "style": "general"},
    {"name": "俯拍", "tags": "top down, bird eye, overhead, flat, geometric", "style": "general"},
    {"name": "平视", "tags": "eye level, straight on, neutral, direct, equal", "style": "general"},
    {"name": "斜角", "tags": "dutch angle, tilted, dynamic, disoriented, dramatic", "style": "general"},
    {"name": "过肩", "tags": "over shoulder, behind, third person, conversation, perspective", "style": "general"},
    {"name": "主体视角", "tags": "first person, POV, perspective, immersive, subjective", "style": "general"},
    {"name": "侧面", "tags": "side view, profile, silhouette, outline, lateral", "style": "general"},
    {"name": "背面", "tags": "back view, rear, from behind, mysterious, following", "style": "general"},
    {"name": "对角线", "tags": "diagonal, dynamic, energy, unbalanced, action", "style": "general"},
    {"name": "三分法", "tags": "rule of thirds, grid, composition, balanced, professional", "style": "general"},
    {"name": "居中", "tags": "centered, symmetrical, formal, direct, balanced", "style": "general"},
    {"name": "对称", "tags": "symmetrical, mirror, balanced, formal, geometric", "style": "general"},
    {"name": "框架构图", "tags": "frame within frame, window, door, layered, depth", "style": "general"},
    {"name": "引导线", "tags": "leading lines, perspective, depth, direction, dynamic", "style": "general"},
    {"name": "留白", "tags": "negative space, minimal, empty, breathing room, focus", "style": "general"},
    {"name": "黄金比例", "tags": "golden ratio, spiral, composition, natural, pleasing", "style": "general"},
    {"name": "曲线构图", "tags": "s curve, winding, graceful, flowing, elegant", "style": "general"},
    {"name": "三角构图", "tags": "triangular, stable, balanced, three points, strong", "style": "general"},
    {"name": "圆形构图", "tags": "circular, round, enclosing, focus, harmony", "style": "general"},
    {"name": "L形构图", "tags": "L shape, corner, solid, balanced, landscape", "style": "general"},
    {"name": "十字构图", "tags": "cross composition, intersection, centered, strong, balanced", "style": "general"},
    {"name": "特写面部", "tags": "close-up face, expressions, emotional, intimate, detailed", "style": "general"},
    {"name": "特写手部", "tags": "close-up hands, detail, gesture, delicate, focus", "style": "general"},
    {"name": "特写脚步", "tags": "close-up feet, detail, shoes, walking, ground", "style": "general"},
    {"name": "特写物品", "tags": "close-up object, macro, detail, texture, product", "style": "general"},
    {"name": "双人镜头", "tags": "two shot, pair, interaction, dialogue, relationship", "style": "general"},
    {"name": "三人镜头", "tags": "three shot, group, interaction, balanced, trio", "style": "general"},
    {"name": "群像", "tags": "group shot, crowd, many, ensemble, wide", "style": "general"},
    {"name": "前后景", "tags": "foreground background, depth, layered, focus, bokeh", "style": "general"},
    {"name": "浅景深", "tags": "shallow depth of field, bokeh, blur, focused, dreamy", "style": "general"},
    {"name": "深景深", "tags": "deep depth of field, sharp, all in focus, detailed", "style": "general"},
    {"name": "焦外", "tags": "out of focus, blurry, dreamy, soft, abstract", "style": "general"},
    {"name": "慢速", "tags": "slow shutter, motion blur, ghosting, long exposure", "style": "general"},
    {"name": "快速", "tags": "fast shutter, frozen, crisp, action, stop motion", "style": "general"},
    {"name": "摇镜", "tags": "panning, motion, speed, directional, blurred background", "style": "general"},
    {"name": "推轨", "tags": "dolly shot, moving, tracking, follow, cinematic", "style": "general"},
    {"name": "变焦", "tags": "zoom, dolly zoom, vertigo, dramatic, pull focus", "style": "general"},
    {"name": "手持", "tags": "handheld, shaky, raw, documentary, intimate", "style": "general"},
    {"name": "稳定", "tags": "tripod, stable, steady, professional, smooth", "style": "general"},
    {"name": "航拍", "tags": "aerial, drone, bird's eye, top, landscape", "style": "general"},
    {"name": "水下摄影", "tags": "underwater shot, submerged, aquatic, blue, floating", "style": "general"},
    {"name": "夜视", "tags": "night vision, green tint, dark, military, surveillance", "style": "general"},
    {"name": "红外", "tags": "infrared, thermal, heat, colored, surreal, scientific", "style": "general"},
    {"name": "鱼眼", "tags": "fisheye, ultra wide, distorted, curved, spherical", "style": "general"},
    {"name": "广角", "tags": "wide angle, expansive, dramatic, distorted, grand", "style": "general"},
    {"name": "标准", "tags": "normal lens, natural, realistic, neutral, standard view", "style": "general"},
    {"name": "长焦", "tags": "telephoto, compressed, distant, intimate, portrait", "style": "general"},
    {"name": "微距", "tags": "macro, extreme detail, tiny, close, magnification", "style": "general"},
    {"name": "移轴", "tags": "tilt shift, miniature, selective focus, diorama, toy", "style": "general"},
    {"name": "光线追踪", "tags": "ray traced, realistic lighting, reflections, shadows, cgi", "style": "general"},
    {"name": "冷暖对比", "tags": "warm cold contrast, blue orange, complementary, vibrant", "style": "general"},
    {"name": "单色", "tags": "monochrome, black and white, grayscale, classic, moody", "style": "general"},
    {"name": "高饱和度", "tags": "high saturation, vivid, colorful, pop, vibrant", "style": "general"},
    {"name": "低饱和度", "tags": "low saturation, muted, faded, desaturated, moody", "style": "general"},
    {"name": "高对比", "tags": "high contrast, stark, dramatic, chiaroscuro, bold", "style": "general"},
    {"name": "低对比", "tags": "low contrast, soft, flat, dreamy, gentle", "style": "general"},
    {"name": "明亮", "tags": "bright, high key, overexposed, airy, positive", "style": "general"},
    {"name": "黑暗", "tags": "dark, low key, underexposed, moody, shadows, noir", "style": "general"},
    {"name": "暖色调", "tags": "warm tone, yellow, orange, cozy, sunset", "style": "general"},
    {"name": "冷色调", "tags": "cool tone, blue, cyan, cold, serene, technology", "style": "general"},
    {"name": "复古", "tags": "vintage, retro, old, film grain, nostalgic, classic", "style": "general"},
    {"name": "日系", "tags": "japanese style, clean, soft, bright, airy, minimalist", "style": "general"},
    {"name": "赛博朋克", "tags": "cyberpunk, neon, futuristic, dark, rain, tech", "style": "general"},
    {"name": "蒸汽波", "tags": "vaporwave, retro, neon, glitch, aesthetic, 80s", "style": "general"},
    {"name": "胶片", "tags": "film look, grain, analog, warm, textured, classic", "style": "general"},
    {"name": "宝丽来", "tags": "polaroid, instant, white border, square, retro, casual", "style": "general"},
    {"name": "监视器", "tags": "CCTV, security cam, surveillance, grainy, wide angle", "style": "general"},
    {"name": "门缝视角", "tags": "door gap, peeking, voyeur, narrow, secret", "style": "general"},
    {"name": "窗边", "tags": "by window, natural light, frame, reflection, scenery", "style": "general"},
    {"name": "镜面", "tags": "mirror, reflection, double, symmetry, vanity", "style": "general"},
    {"name": "水面倒影", "tags": "water reflection, mirror, lake, puddle, symmetrical", "style": "general"},
    {"name": "剪影", "tags": "silhouette, dark, outline, backlight, dramatic", "style": "general"},
    {"name": "阴影", "tags": "shadow play, cast shadow, pattern, silhouette, graphic", "style": "general"},
    {"name": "半透明", "tags": "see through, translucent, overlay, ghost, layered", "style": "general"},
    {"name": "倒置", "tags": "upside down, inverted, disoriented, surreal, perspective", "style": "general"},
    {"name": "多重曝光", "tags": "multiple exposure, layered, double, ghost, artistic", "style": "general"},
    {"name": "全景", "tags": "panoramic, wide, sweeping, landscape, 360", "style": "general"},
    {"name": "拼接", "tags": "stitched, composite, wide, panoramic, seamless", "style": "general"},
    {"name": "分屏", "tags": "split screen, multi view, comparison, simultaneous", "style": "general"},
    {"name": "小窗", "tags": "picture in picture, inset, overlay, secondary", "style": "general"},
    {"name": "漫画分格", "tags": "comic panel, manga panel, sequential, grid, storyboard", "style": "general"},
    {"name": "焦点堆叠", "tags": "focus stacking, sharp, macro, detailed, depth extended", "style": "general"},
    {"name": "渐变滤镜", "tags": "gradient filter, ND grad, sky, landscape, balanced", "style": "general"},
    {"name": "十字滤镜", "tags": "cross screen filter, star, lights, sparkle, glamour", "style": "general"},
    {"name": "柔焦", "tags": "soft focus, dreamy, blur, romantic, gentle, hazy", "style": "general"},
    {"name": "雾镜", "tags": "mist filter, foggy, atmospheric, soft, dreamlike", "style": "general"},
    {"name": "偏光镜", "tags": "polarizer, CPL, rich colors, reflection removed, contrast", "style": "general"},
    {"name": "渐晕", "tags": "vignette, dark corners, focus center, classic, dramatic", "style": "general"},
    {"name": "光晕", "tags": "lens flare, glare, sun flare, bright, cinematic", "style": "general"},
    {"name": "噪点", "tags": "grain noise, film grain, textured, analog, vintage", "style": "general"},
    {"name": "像素化", "tags": "pixelated, 8bit, retro game, blocky, low res", "style": "general"},
    {"name": "仿油画", "tags": "oil painting effect, painterly, brush strokes, artistic", "style": "general"},
    {"name": "水彩", "tags": "watercolor, wash, flowing, artistic, soft edges", "style": "general"},
    {"name": "素描", "tags": "sketch, pencil, line art, drawing, monochrome", "style": "general"},
    {"name": "3D渲染", "tags": "3D render, CGI, computer graphics, modeled, realistic", "style": "general"},
    {"name": "二次元", "tags": "anime style, cel shaded, 2D, japanese art, flat colors", "style": "general"},
]


def write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    # Read existing
    existing = []
    if path.exists():
        with open(path, 'r', encoding='utf-8') as f:
            existing = json.load(f)
    # Merge: keep existing first, then append new ones (avoid exact name dupes)
    existing_names = {e['name'] for e in existing}
    merged = list(existing)
    for item in data:
        if item['name'] not in existing_names:
            merged.append(item)
            existing_names.add(item['name'])
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
    print(f"  {path.name}: {len(existing)} -> {len(merged)} 条 (+{len(merged)-len(existing)})")


# ============================================================
# 5. anima/lora角色.json — LoRA角色 (现有6条 → 补100条)
# ============================================================
LORA_NEW = [
    {"name": "甘雨 - 蓝发麒麟", "tags": "ganyu, genshin impact, 1girl, blue hair, long hair, horns, qipao, bell ornament, black pantyhose, elegant, cryo", "style": "general"},
    {"name": "刻晴 - 紫发雷厉", "tags": "keqing, genshin impact, 1girl, purple hair, twin tails, cat ears hair, bell ornament, white dress, purple pantyhose, elegant, electro", "style": "general"},
    {"name": "胡桃 - 双马尾", "tags": "hu tao, genshin impact, 1girl, brown hair, long hair, dark circles, hat, butterfly ornament, black and red outfit, playful, pyro", "style": "general"},
    {"name": "雷电将军 - 紫发威严", "tags": "raiden shogun, genshin impact, 1girl, purple hair, long hair, braid, bangs, kimono, sword, serious, electro archon", "style": "general"},
    {"name": "纳西妲 - 白毛萝莉", "tags": "nahida, genshin impact, 1girl, white hair, short hair, green eyes, cape, shorts, barefoot, dendro archon, cute", "style": "general"},
    {"name": "芙宁娜 - 蓝白礼装", "tags": "furina, genshin impact, 1girl, blue hair, heterochromia, blue and white outfit, cape, hat, elegant, hydro archon", "style": "general"},
    {"name": "神里绫华 - 和服公主", "tags": "kamisato ayaka, genshin impact, 1girl, blue hair, hime cut, japanese clothes, fan, elegant, cryo, dignified", "style": "general"},
    {"name": "宵宫 - 金发元气", "tags": "yoimiya, genshin impact, 1girl, blonde hair, ponytail, bandages, open jacket, shorts, cheerful, pyro", "style": "general"},
    {"name": "夜兰 - 黑丝御姐", "tags": "yelan, genshin impact, 1girl, dark blue hair, long hair, black bodysuit, pantyhose, dice, elegant, hydro", "style": "general"},
    {"name": "妮露 - 红发舞娘", "tags": "nilou, genshin impact, 1girl, red hair, long hair, flower ornament, dancer, blue and gold outfit, graceful, hydro", "style": "general"},
    {"name": "派蒙 - 飞行矮堇瓜", "tags": "paimon, genshin impact, 1girl, white hair, short hair, crown, floating, white blue dress, cute, mascot", "style": "general"},
    {"name": "八重神子 - 粉狐巫女", "tags": "yae miko, genshin impact, 1girl, pink hair, long hair, fox ears, shrine maiden, kimono, mischievous, electro", "style": "general"},
    {"name": "琪亚娜 - 白练", "tags": "kiana kaslana, honkai impact 3rd, 1girl, white hair, long hair, side ponytail, blue eyes, battle suit, valkyrie", "style": "general"},
    {"name": "布洛妮娅 - 银狼", "tags": "bronya zaychik, honkai impact 3rd, 1girl, gray hair, twin tails, blue eyes, mecha, russian, silverwolf", "style": "general"},
    {"name": "希儿 - 蓝黑双生", "tags": "seele vollerei, honkai impact 3rd, 1girl, blue hair, long hair, red eyes, black dress, cloak, dual personality", "style": "general"},
    {"name": "符华 - 神州仙人", "tags": "fu hua, honkai impact 3rd, 1girl, brown hair, long hair, ponytail, chinese dress, martial arts, valkyrie", "style": "general"},
    {"name": "爱莉希雅 - 粉发妖精", "tags": "elysia, honkai impact 3rd, 1girl, pink hair, long hair, elf ears, pink dress, flower theme, gentle", "style": "general"},
    {"name": "薪炎之律者", "tags": "herrscher of flamescion, kiana, honkai impact 3rd, 1girl, white hair, flames, crown, white and gold armor, powerful", "style": "general"},
    {"name": "始源之律者", "tags": "herrscher of origin, elysia, honkai impact 3rd, 1girl, pink hair, crystal, wings, divine, ethereal", "style": "general"},
    {"name": "流萤 - 机甲少女", "tags": "firefly, honkai star rail, 1girl, silver hair, short hair, mecha armor, green eyes, samurai, stunning", "style": "general"},
    {"name": "卡芙卡 - 紫色魅力", "tags": "kafka, honkai star rail, 1girl, purple hair, long hair, coat, sunglasses, pistol, domineering, elegant", "style": "general"},
    {"name": "镜流 - 白发剑仙", "tags": "jingliu, honkai star rail, 1girl, white hair, long hair, blindfold, sword, cold, powerful", "style": "general"},
    {"name": "布洛妮娅·兰德 - 银狼", "tags": "bronya rand, honkai star rail, 1girl, gray hair, twin tails, military uniform, cape, commander, ice", "style": "general"},
    {"name": "希露瓦 - 摇滚吉他", "tags": "serval, honkai star rail, 1girl, gray hair, long hair, guitar, rock, punk style, mechanics", "style": "general"},
    {"name": "克拉拉 - 机械助手", "tags": "clara, honkai star rail, 1girl, brown hair, long hair, red eyes, dress, robot companion, cute", "style": "general"},
    {"name": "阿米娅 - 兔耳领袖", "tags": "amiya, arknights, 1girl, brown hair, long hair, rabbit ears, hood, black coat, leader, cute", "style": "general"},
    {"name": "陈 - 赤霄", "tags": "chen, arknights, 1girl, blue hair, long hair, ponytail, dragon horns, sword, police, lungmen", "style": "general"},
    {"name": "能天使 - 乐天派", "tags": "exusiai, arknights, 1girl, white hair, short hair, halo, wings, gun, smiling, penguin logistics", "style": "general"},
    {"name": "德克萨斯 - 灰狼", "tags": "texas, arknights, 1girl, gray hair, long hair, wolf ears, tail, black suit, sword, cool", "style": "general"},
    {"name": "斯卡蒂 - 沉默猎人", "tags": "skadi, arknights, 1girl, white hair, long hair, hood, greatsword, abyss, hunter, silent", "style": "general"},
    {"name": "W - 危险佣兵", "tags": "w, arknights, 1girl, white hair, short hair, black outfit, explosives, mischievous, sarkaz", "style": "general"},
    {"name": "霜星 - 雪之少女", "tags": "frostnova, arknights, 1girl, white hair, long hair, snow, winter coat, gentle, infected", "style": "general"},
    {"name": "缪尔赛思 - 精灵学者", "tags": "muelsyse, arknights, 1girl, green hair, long hair, elf ears, white coat, nature, elegant", "style": "general"},
    {"name": "浊心斯卡蒂", "tags": "skadi the corrupting heart, arknights, 1girl, white hair, long hair, black and red dress, tentacles, abyss, eerie", "style": "general"},
    {"name": "初音未来 - 经典", "tags": "hatsune miku, vocaloid, 1girl, turquoise hair, long hair, twin tails, blue eyes, school uniform, singer", "style": "general"},
    {"name": "镜音铃 - 元气", "tags": "kagamine rin, vocaloid, 1girl, blonde hair, short hair, ponytail, yellow outfit, energetic, vocaloid", "style": "general"},
    {"name": "巡音流歌 - 粉色长发", "tags": "megurine luka, vocaloid, 1girl, pink hair, long hair, gentle, elegant, mature, vocaloid", "style": "general"},
    {"name": "MEIKO - 酒红", "tags": "meiko, vocaloid, 1girl, brown hair, short hair, red outfit, mature, vocaloid, singer", "style": "general"},
    {"name": "GUMI - 绿发", "tags": "gumi, vocaloid, 1girl, green hair, long hair, ponytail, blue eyes, cheerful, vocaloid", "style": "general"},
    {"name": "亚丝娜 - 细剑使", "tags": "asuna yuuki, sword art online, 1girl, orange hair, long hair, blue eyes, white and red outfit, knight, brave", "style": "general"},
    {"name": "结城明日奈", "tags": "asuna yuuki, sword art online, 1girl, orange hair, long hair, school uniform, gentle, determined", "style": "general"},
    {"name": "诗乃 - 狙击手", "tags": "sinon, sword art online, 1girl, purple hair, long hair, side ponytail, sniper, ggo outfit, glasses", "style": "general"},
    {"name": "爱丽丝 - 整合骑士", "tags": "alice zuberg, sword art online, 1girl, blonde hair, long hair, blue eyes, armor, holy knight, dignified", "style": "general"},
    {"name": "Saber - 亚瑟王", "tags": "saber, fate, artoria pendragon, 1girl, blonde hair, bun, green eyes, armor, sword, king, majestic", "style": "general"},
    {"name": "远坂凛 - 魔术师", "tags": "rin tosaka, fate, 1girl, black hair, long hair, twin tails, red dress, confident, magus", "style": "general"},
    {"name": "间桐樱 - 黑化", "tags": "sakura matou, fate, 1girl, purple hair, long hair, purple dress, gentle, dark, mysterious", "style": "general"},
    {"name": "阿尔托莉雅·Caster", "tags": "caster artoria, fate, 1girl, white hair, long hair, staff, white dress, divine, majestic", "style": "general"},
    {"name": "贞德 - 圣女", "tags": "jeanne d arc, fate, 1girl, blonde hair, long hair, blue eyes, armor, flag, holy, determined", "style": "general"},
    {"name": "尼禄 - 罗马之花", "tags": "nero claudius, fate, 1girl, red hair, long hair, green eyes, white and red dress, rose, confident", "style": "general"},
    {"name": "玉藻前 - 九尾狐", "tags": "tamamo no mae, fate, 1girl, blonde hair, long hair, fox ears, tail, miko, mischievous", "style": "general"},
    {"name": "冲田总司 - 天才剑士", "tags": "okita souji, fate, 1girl, black hair, ponytail, blue eyes, shinsengumi, sword, sadistic", "style": "general"},
    {"name": "莫德雷德 - 叛逆骑士", "tags": "mordred, fate, 1girl, blonde hair, short hair, red armor, helmet, rebellious, knight", "style": "general"},
    {"name": "两仪式 - 根源式", "tags": "ryougi shiki, kara no kyoukai, 1girl, black hair, long hair, kimono, knife, mysterious, calm", "style": "general"},
    {"name": "浅上藤乃 - 扭曲", "tags": "fujino asagami, kara no kyoukai, 1girl, brown hair, long hair, school uniform, glasses, gentle, twisted", "style": "general"},
    {"name": "鹿目圆 - 魔法少女", "tags": "madoka kaname, madoka magica, 1girl, pink hair, long hair, twin tails, pink dress, magical girl, kind", "style": "general"},
    {"name": "晓美焰 - 轮回", "tags": "homura akemi, madoka magica, 1girl, black hair, long hair, purple eyes, school uniform, shield, determined", "style": "general"},
    {"name": "巴麻美 - 学姐", "tags": "mami tomoe, madoka magica, 1girl, blonde hair, long hair, curls, yellow dress, musketeer, elegant", "style": "general"},
    {"name": "美树沙耶香 - 蓝发", "tags": "sayaka miki, madoka magica, 1girl, blue hair, short hair, blue dress, sword, magical girl, passionate", "style": "general"},
    {"name": "佐仓杏子 - 红发", "tags": "kyoko sakura, madoka magica, 1girl, red hair, long hair, ponytail, red dress, spear, wild", "style": "general"},
    {"name": "雷姆 - 蓝发女仆", "tags": "rem, re zero, 1girl, blue hair, short hair, maid outfit, horn, headband, loyal, dedicated", "style": "general"},
    {"name": "拉姆 - 粉发女仆", "tags": "ram, re zero, 1girl, pink hair, short hair, maid outfit, horn, headband, tsundere, proud", "style": "general"},
    {"name": "爱蜜莉雅 - 银发精灵", "tags": "emilia, re zero, 1girl, silver hair, long hair, purple eyes, elf, white dress, gentle, elegant", "style": "general"},
    {"name": "碧翠丝 - 禁书库", "tags": "beatrice, re zero, 1girl, blonde hair, long hair, curls, lolita dress, tsundere, librarian", "style": "general"},
    {"name": "雪之下雪乃 - 冰美人", "tags": "yukino yukinoshita, oregairu, 1girl, black hair, long hair, straight, cool, beautiful, serious", "style": "general"},
    {"name": "由比滨结衣 - 团子", "tags": "yui yuigahama, oregairu, 1girl, brown hair, ponytail, warm, friendly, cheerful, cute", "style": "general"},
    {"name": "霞之丘诗羽 - 学姐", "tags": "utaha kasumigaoka, saekano, 1girl, black hair, long hair, stockings, tsundere, writer, beautiful", "style": "general"},
    {"name": "加藤惠 - 路人女主", "tags": "megumi kato, saekano, 1girl, black hair, medium hair, beret, calm, natural, cute", "style": "general"},
    {"name": "樱岛麻衣 - 兔女郎", "tags": "mai sakurajima, bunny girl senpai, 1girl, black hair, long hair, bunny suit, elegant, mature, actress", "style": "general"},
    {"name": "牧之原翔子", "tags": "shoko makinohara, bunny girl senpai, 1girl, brown hair, long hair, gentle, school uniform, kind", "style": "general"},
    {"name": "古贺朋美", "tags": "tomi koga, bunny girl senpai, 1girl, black hair, long hair, twin tails, energetic, school uniform, cute", "style": "general"},
    {"name": "丰滨和香", "tags": "waka丰滨, bunny girl senpai, 1girl, brown hair, short hair, idolsinger, energetic, school uniform", "style": "general"},
    {"name": "时崎狂三 - 刻刻帝", "tags": "kurumi tokisaki, date a live, 1girl, black hair, long hair, twin tails, red eyes, gothic lolita, clock", "style": "general"},
    {"name": "鸢一折纸 - 天使", "tags": "origami tobiichi, date a live, 1girl, white hair, short hair, blue eyes, angel, astral dress", "style": "general"},
    {"name": "夜刀神十香 - 公主", "tags": "toka yatogami, date a live, 1girl, purple hair, long hair, crystal dress, sword, energetic", "style": "general"},
    {"name": "四糸乃 - 冰之精灵", "tags": "yoshino, date a live, 1girl, blue hair, long hair, hood, rabbit puppet, shy, gentle", "style": "general"},
    {"name": "C.C. - 魔女", "tags": "c.c., code geass, 1girl, green hair, long hair, golden eyes, pizza, mysterious, immortal", "style": "general"},
    {"name": "御坂美琴 - 超电磁炮", "tags": "misaka mikoto, toaru, 1girl, brown hair, short hair, school uniform, tsundere, railgun, elector", "style": "general"},
    {"name": "食蜂操祈 - 心理掌握", "tags": "shokuhou misaki, toaru, 1girl, blonde hair, long hair, star eyes, school uniform, telepath", "style": "general"},
    {"name": "白井黑子 - 空间移动", "tags": "kuroko shirai, toaru, 1girl, brown hair, twin tails, school uniform, teleporter, obsessed", "style": "general"},
    {"name": "佐天泪子", "tags": "ruiko saten, toaru, 1girl, black hair, long hair, school uniform, cheerful, friend, casual", "style": "general"},
    {"name": "黄泉 - 无口刀客", "tags": "hoyomi, 1girl, silver hair, long hair, sword, dark outfit, cool, expressionless", "style": "general"},
    {"name": "艾琳 - 圣骑士", "tags": "erinn, 1girl, blonde hair, long hair, armor, sword, paladin, holy, noble", "style": "general"},
    {"name": "贝尔 - 白毛兽耳", "tags": "bell, 1girl, white hair, long hair, cat ears, tail, dress, adventurer, cheerful", "style": "general"},
    {"name": "温迪 - 风神", "tags": "venti, genshin impact, 1boy, short, green outfit, lyre, bard, wind, mischievous", "style": "general"},
    {"name": "钟离 - 岩王帝君", "tags": "zhongli, genshin impact, 1boy, brown hair, long hair, suit, contract, wise, geo", "style": "general"},
    {"name": "枫原万叶 - 浪人", "tags": "kazuha, genshin impact, 1boy, red and white hair, ponytail, samurai, maple leaf, wanderer", "style": "general"},
    {"name": "达达利亚 - 公子", "tags": "tartaglia, childe, genshin impact, 1boy, ginger hair, mask, bow, hydro, combat", "style": "general"},
    {"name": "艾尔海森 - 书记官", "tags": "alhaitham, genshin impact, 1boy, gray hair, green eyes, muscular, book, scholar, dendro", "style": "general"},
    {"name": "绫人 - 家主", "tags": "kamisato ayato, genshin impact, 1boy, blue hair, elegant, sword, hydro, composed", "style": "general"},
    {"name": "那维莱特 - 水龙王", "tags": "neuvillette, genshin impact, 1boy, white hair, long hair, blue suit, judge, hydro dragon", "style": "general"},
    {"name": "薰儿 - 青衣", "tags": "xun er, battle through the heavens, 1girl, blue hair, long hair, elegant, green dress, noble", "style": "general"},
    {"name": "小医仙 - 毒女", "tags": "xiao yi xian, battle through the heavens, 1girl, white hair, long hair, ethereal, kind, poisonous", "style": "general"},
    {"name": "美杜莎 - 蛇人女王", "tags": "medusa, battle through the heavens, 1girl, purple hair, long hair, snake eyes, queen, seductive", "style": "general"},
    {"name": "云韵 - 云岚宗", "tags": "yun yun, battle through the heavens, 1girl, blue hair, long hair, elegant, sword, master, mature", "style": "general"},
    {"name": "绫波丽 - 无口", "tags": "rei ayanami, evangelion, 1girl, blue hair, short hair, red eyes, school uniform, plugsuit, mysterious", "style": "general"},
    {"name": "明日香 - 傲娇", "tags": "asuka langley, evangelion, 1girl, red hair, twin tails, plugsuit, tsundere, pilot", "style": "general"},
    {"name": "葛城美里", "tags": "misato katsuragi, evangelion, 1girl, purple hair, short hair, jacket, commander, mature, beer", "style": "general"},
    {"name": "真希波 - 眼镜娘", "tags": "mari illustrious, evangelion, 1girl, brown hair, twin tails, glasses, plugsuit, cheerful", "style": "general"},
    {"name": "秋山澪 - 贝斯手", "tags": "mio akiyama, k on, 1girl, black hair, long hair, bass, shy, school uniform", "style": "general"},
    {"name": "中野梓 - 吉他", "tags": "azusa nakano, k on, 1girl, black hair, twin tails, guitar, cat ears, serious, cute", "style": "general"},
    {"name": "平泽唯 - 天然呆", "tags": "yui hirasawa, k on, 1girl, brown hair, short hair, guitar, cheerful, airhead", "style": "general"},
    {"name": "田井中律 - 鼓手", "tags": "ritsu tainaka, k on, 1girl, brown hair, short hair, drums, leader, energetic", "style": "general"},
    {"name": "琴吹䌷 - 键盘", "tags": "tsumugi kotobuki, k on, 1girl, brown hair, long hair, keyboard, rich, elegant, kind", "style": "general"},
    {"name": "蝴蝶忍 - 虫柱", "tags": "shinobu kocho, demon slayer, 1girl, black hair, purple eyes, butterfly, insect pillar, gentle smile", "style": "general"},
    {"name": "甘露寺蜜璃 - 恋柱", "tags": "mitsuri kanroji, demon slayer, 1girl, pink hair, green eyes, love pillar, strong, emotional", "style": "general"},
    {"name": "栗花落香奈乎", "tags": "kanao tsuruyi, demon slayer, 1girl, black hair, butterfly hairpin, gentle, quiet", "style": "general"},
    {"name": "胡蝶カナエ", "tags": "kanae kocho, demon slayer, 1girl, black hair, purple eyes, smile, gentle, flower", "style": "general"},
    {"name": "灶门祢豆子", "tags": "nezuko kamado, demon slayer, 1girl, black hair, pink eyes, bamboo muzzle, demon, cute", "style": "general"},
]


if __name__ == '__main__':
    print("=== 生成魔导书补充数据 ===\n")

    print("[1/5] lighting/lighting.json ...")
    write_json(DATA / "lighting" / "lighting.json", LIGHTING_NEW)

    print("[2/5] pose_action/normal_posture.json ...")
    write_json(DATA / "pose_action" / "normal_posture.json", POSE_NEW)

    print("[3/5] scene/environment.json ...")
    write_json(DATA / "scene" / "environment.json", SCENE_NEW)

    print("[4/5] shot/framing.json ...")
    write_json(DATA / "shot" / "framing.json", FRAMING_NEW)

    print("[5/5] anima/lora角色.json ...")
    write_json(DATA / "anima" / "lora角色.json", LORA_NEW)

    print("\n✅ 完成！")
